{
	"Name": "Windowing",
	"Type": "Runtime",
	"Extern": ["Glfw", "VulkanLoader"],
	"Libraries": {
		"x64": {
			"Windows": {
				"MSVC": [
					"user32.lib",
					"gdi32.lib",
					"Shell32.lib"
				],
				"MinGW": [
					"user32",
					"gdi32",
					"shell32",
					"stdc++fs"
				]
			},
			"Linux": {
				"GCC": [
					"pthread",
					"dl"
				]
			}
		}
	},
	"Modules": ["Core", "Rendering", "AssetCore", "Math", "OpenGL2", "Vulkan"]
}